import SphericalHarmonics.Fischer

open scoped ENNReal MeasureTheory

namespace SphericalHarmonics

/-- The canonical map from continuous functions on `S²` to `L²(S²)` for `rotationMeasure`. -/
noncomputable abbrev continuousToLp :
    C(S2, ℝ) →L[ℝ] MeasureTheory.Lp ℝ 2 rotationMeasure :=
  ContinuousMap.toLp 2 rotationMeasure ℝ

/-- The algebra homomorphism sending an ambient polynomial to its restriction to `S²`. -/
noncomputable def restrictToSphereAlgHom : Poly3 →ₐ[ℝ] C(S2, ℝ) :=
  MvPolynomial.aeval coord

@[simp] theorem restrictToSphereAlgHom_apply (p : Poly3) :
    restrictToSphereAlgHom p = restrictToSphere p := by
  ext x
  refine (show ∀ p : Poly3, (restrictToSphereAlgHom p) x = (restrictToSphere p) x from ?_) p
  intro p
  refine MvPolynomial.induction_on (motive := fun p : Poly3 =>
    (restrictToSphereAlgHom p) x = (restrictToSphere p) x) p ?_ ?_ ?_
  · intro a
    simp [restrictToSphereAlgHom, restrictToSphere]
  · intro p q hp hq
    simp [hp, hq]
  · intro p i hp
    calc
      (restrictToSphereAlgHom (p * MvPolynomial.X i)) x
          = (restrictToSphereAlgHom p x) * coord i x := by
              simp [restrictToSphereAlgHom, MvPolynomial.aeval_def]
      _ = (restrictToSphere p x) * x.1 i := by
              simpa [coord_apply] using congrArg (fun t : ℝ => t * x.1 i) hp
      _ = (restrictToSphere (p * MvPolynomial.X i)) x := by
              simp [restrictToSphere]

/-- The subalgebra of continuous functions on `S²` generated by ambient polynomial restrictions. -/
noncomputable def polynomialSubalgebra : Subalgebra ℝ C(S2, ℝ) :=
  restrictToSphereAlgHom.range

/-- The linear span of polynomial restrictions on `S²`. -/
noncomputable def continuousPolynomialSpan : Submodule ℝ C(S2, ℝ) :=
  Submodule.span ℝ (Set.range restrictToSphere)

/-- The `L²`-span of polynomial restrictions on `S²`. -/
noncomputable def polynomialLpSpan : Submodule ℝ (MeasureTheory.Lp ℝ 2 rotationMeasure) :=
  continuousPolynomialSpan.map continuousToLp.toLinearMap

@[simp] theorem coord_mem_polynomialSubalgebra (i : Fin 3) : coord i ∈ polynomialSubalgebra := by
  refine ⟨MvPolynomial.X i, ?_⟩
  ext x
  simp [restrictToSphereAlgHom, coord, MvPolynomial.aeval_def]

theorem polynomialSubalgebra_separatesPoints : polynomialSubalgebra.SeparatesPoints := by
  intro x y hxy
  have hxy' : (x : E3) ≠ (y : E3) := by
    intro h
    apply hxy
    exact Subtype.ext h
  obtain ⟨i, hi⟩ : ∃ i : Fin 3, x.1 i ≠ y.1 i := by
    classical
    by_contra h
    apply hxy'
    ext i
    by_contra hi'
    exact h ⟨i, hi'⟩
  refine ⟨coord i, ⟨coord i, coord_mem_polynomialSubalgebra i, rfl⟩, ?_⟩
  simpa [coord_apply] using hi

/-- Polynomial restrictions are dense in `C(S², ℝ)`. -/
theorem polynomialSubalgebra_topologicalClosure_eq_top :
    polynomialSubalgebra.topologicalClosure = ⊤ :=
  ContinuousMap.subalgebra_topologicalClosure_eq_top_of_separatesPoints _
    polynomialSubalgebra_separatesPoints

theorem polynomialSubalgebra_subset_continuousPolynomialSpan :
    (polynomialSubalgebra : Set C(S2, ℝ)) ⊆ continuousPolynomialSpan := by
  intro f hf
  rcases hf with ⟨p, rfl⟩
  exact Submodule.subset_span ⟨p, (restrictToSphereAlgHom_apply p).symm⟩

/-- The span of polynomial restrictions is dense in `C(S², ℝ)`. -/
theorem continuousPolynomialSpan_topologicalClosure_eq_top :
    continuousPolynomialSpan.topologicalClosure = ⊤ := by
  have hDenseA : Dense (polynomialSubalgebra : Set C(S2, ℝ)) := by
    apply dense_iff_closure_eq.2
    simpa [Subalgebra.topologicalClosure_coe] using congrArg
      (fun A : Subalgebra ℝ C(S2, ℝ) => (A : Set C(S2, ℝ)))
      polynomialSubalgebra_topologicalClosure_eq_top
  rw [← Submodule.dense_iff_topologicalClosure_eq_top]
  exact hDenseA.mono polynomialSubalgebra_subset_continuousPolynomialSpan

theorem continuousToLp_denseRange : DenseRange continuousToLp := by
  have hp : (2 : ℝ≥0∞) ≠ ∞ := by
    norm_num
  simpa [continuousToLp] using
    (ContinuousMap.toLp_denseRange (α := S2) (E := ℝ) (μ := rotationMeasure) (𝕜 := ℝ)
      (p := (2 : ℝ≥0∞)) hp)

/-- Polynomial restrictions are dense in `L²(S²)` for `rotationMeasure`. -/
theorem polynomialLpSpan_topologicalClosure_eq_top :
    polynomialLpSpan.topologicalClosure = ⊤ := by
  exact continuousToLp_denseRange.topologicalClosure_map_submodule
    (s := continuousPolynomialSpan) continuousPolynomialSpan_topologicalClosure_eq_top

/-- The degree-`n` sector inside `L²(S²)`, obtained by mapping the continuous sector into `L²`. -/
noncomputable def sectorL2 (n : ℕ) : Submodule ℝ (MeasureTheory.Lp ℝ 2 rotationMeasure) :=
  (sector n).map continuousToLp.toLinearMap

theorem continuousToLp_mem_sectorL2 {n : ℕ} {f : C(S2, ℝ)} (hf : f ∈ sector n) :
    continuousToLp f ∈ sectorL2 n :=
  ⟨f, hf, rfl⟩

theorem polynomialLpSpan_le_iSup_sectorL2_of_sector_decomposition
    (hdecomp : ∀ p : Poly3, restrictToSphere p ∈ ⨆ n : ℕ, sector n) :
    polynomialLpSpan ≤ ⨆ n : ℕ, sectorL2 n := by
  rw [polynomialLpSpan, continuousPolynomialSpan, Submodule.map_span]
  refine Submodule.span_le.mpr ?_
  rintro _ ⟨f, ⟨p, rfl⟩, rfl⟩
  have hp : restrictToSphere p ∈ ⨆ n : ℕ, sector n := hdecomp p
  have hmap :
      Submodule.map continuousToLp.toLinearMap (⨆ n : ℕ, sector n) = ⨆ n : ℕ, sectorL2 n := by
    simp [sectorL2, Submodule.map_iSup]
  have hmem : continuousToLp (restrictToSphere p) ∈
      Submodule.map continuousToLp.toLinearMap (⨆ n : ℕ, sector n) := ⟨_, hp, rfl⟩
  simpa [hmap] using hmem

/-- If every polynomial restriction on `S²` decomposes into harmonic degree sectors, then the
corresponding `L²` sectors are complete. This is the bridge from Fischer decomposition to
Hilbert-space completeness. -/
theorem sectorL2_topologicalClosure_eq_top_of_sector_decomposition
    (hdecomp : ∀ p : Poly3, restrictToSphere p ∈ ⨆ n : ℕ, sector n) :
    (⨆ n : ℕ, sectorL2 n).topologicalClosure = ⊤ := by
  have hmono :
      polynomialLpSpan.topologicalClosure ≤ (⨆ n : ℕ, sectorL2 n).topologicalClosure :=
    Submodule.topologicalClosure_mono
      (polynomialLpSpan_le_iSup_sectorL2_of_sector_decomposition hdecomp)
  rw [polynomialLpSpan_topologicalClosure_eq_top] at hmono
  exact top_unique hmono

/-- The actual spherical-harmonic sectors are complete in `L²(S²)` because polynomial
restrictions decompose into harmonic degrees by Fischer decomposition. -/
theorem sectorL2_topologicalClosure_eq_top :
    (⨆ n : ℕ, sectorL2 n).topologicalClosure = ⊤ :=
  sectorL2_topologicalClosure_eq_top_of_sector_decomposition restrict_mem_iSup_sector

end SphericalHarmonics
