import SphericalHarmonics.FiniteDimensional
import SphericalHarmonics.LowDegree
import SphericalHarmonics.NorthFixedAmbient
import Mathlib.Data.Sym.Card
import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas

noncomputable section

namespace SphericalHarmonics

open scoped ENNReal

/-- Degree-`n` exponent vectors are the same data as finitely-supported natural functions of total
mass `n`. -/
noncomputable def degreeExponentsEquivNatSum (n : ℕ) :
    DegreeExponents n ≃ {d : Fin 3 →₀ ℕ // d.sum (fun _ => id) = n} where
  toFun d := ⟨d.1, by
    calc
      d.1.sum (fun _ => id) = d.1.degree := by
        simpa [Finsupp.sum_fintype] using (Finsupp.degree_eq_sum d.1).symm
      _ = n := d.2⟩
  invFun d := ⟨d.1, by
    calc
      d.1.degree = d.1.sum (fun _ => id) := by
        simpa [Finsupp.sum_fintype] using (Finsupp.degree_eq_sum d.1)
      _ = n := d.2⟩
  left_inv d := by
    apply Subtype.ext
    rfl
  right_inv d := by
    apply Subtype.ext
    rfl

theorem card_degreeExponents (n : ℕ) :
    Fintype.card (DegreeExponents n) = Nat.multichoose 3 n := by
  classical
  letI : Finite {d : Fin 3 →₀ ℕ // d.sum (fun _ => id) = n} :=
    Finite.of_equiv (DegreeExponents n) (degreeExponentsEquivNatSum n).symm
  letI : Fintype {d : Fin 3 →₀ ℕ // d.sum (fun _ => id) = n} := Fintype.ofFinite _
  rw [Fintype.card_congr (degreeExponentsEquivNatSum n)]
  rw [← Fintype.card_congr (Sym.equivNatSum (Fin 3) n)]
  simpa using Sym.card_sym_eq_multichoose (Fin 3) n

/-- The degree-`n` homogeneous subspace is freely generated by the monomials indexed by
`DegreeExponents n`. -/
noncomputable def homogeneousSubmoduleEquivDegreeExponentsFinsupp (n : ℕ) :
    homogeneousSubmodule n ≃ₗ[ℝ] DegreeExponents n →₀ ℝ := by
  let s : Set (Fin 3 →₀ ℕ) := {d | d.degree = n}
  let e₁ : homogeneousSubmodule n ≃ₗ[ℝ] Finsupp.supported ℝ ℝ s :=
    LinearEquiv.ofEq _ _ <| by
      simpa [s] using
        (MvPolynomial.homogeneousSubmodule_eq_finsupp_supported (σ := Fin 3) (R := ℝ) n)
  let e₂ : Finsupp.supported ℝ ℝ s ≃ₗ[ℝ] s →₀ ℝ :=
    Finsupp.supportedEquivFinsupp (M := ℝ) (R := ℝ) s
  simpa [DegreeExponents, s] using e₁.trans e₂

theorem finrank_homogeneousSubmodule (n : ℕ) :
    Module.finrank ℝ (homogeneousSubmodule n) = Nat.multichoose 3 n := by
  rw [(homogeneousSubmoduleEquivDegreeExponentsFinsupp n).finrank_eq]
  rw [Module.finrank_finsupp_self, card_degreeExponents]

theorem laplacianHomogeneous_surjective (n : ℕ) :
    Function.Surjective (laplacianHomogeneous n) := by
  intro p
  rcases laplacianRadiusSqHomogeneous_surjective n p with ⟨q, hq⟩
  refine ⟨radiusSqMulHomogeneous n q, ?_⟩
  simpa [laplacianRadiusSqHomogeneous] using hq

/-- The kernel of the degree-lowering Laplacian on homogeneous degree-`n+2` polynomials is exactly
the harmonic degree-`n+2` subspace. -/
noncomputable def kerLaplacianHomogeneousEquivHarmonicHomogeneousSubmodule (n : ℕ) :
    LinearMap.ker (laplacianHomogeneous n) ≃ₗ[ℝ] harmonicHomogeneousSubmodule (n + 2) where
  toFun p := ⟨p.1.1, by
    refine Submodule.mem_inf.mpr ⟨p.1.2, ?_⟩
    have hp : laplacianHomogeneous n p.1 = 0 := by
      simpa [LinearMap.mem_ker] using p.2
    have hp0 : laplacian p.1.1 = 0 := congrArg Subtype.val hp
    simpa [harmonicSubmodule, LinearMap.mem_ker] using hp0⟩
  invFun p := ⟨⟨p.1, p.2.1⟩, by
    have hp : laplacian p.1 = 0 := by
      simpa [harmonicSubmodule, LinearMap.mem_ker] using p.2.2
    simpa [LinearMap.mem_ker, laplacianHomogeneous] using hp⟩
  map_add' p q := by
    ext x
    rfl
  map_smul' a p := by
    ext x
    rfl
  left_inv p := by
    apply Subtype.ext
    rfl
  right_inv p := by
    apply Subtype.ext
    rfl

private theorem multichoose_three_two_step (n : ℕ) :
    Nat.multichoose 3 (n + 2) = Nat.multichoose 3 n + (2 * (n + 2) + 1) := by
  rw [Nat.multichoose_succ_succ 2 (n + 1), Nat.multichoose_succ_succ 2 n]
  simp [Nat.multichoose_two]
  omega

private theorem finrank_harmonicHomogeneousSubmodule_succ_succ (n : ℕ) :
    Module.finrank ℝ (harmonicHomogeneousSubmodule (n + 2)) = 2 * (n + 2) + 1 := by
  have hsurj : Function.Surjective (laplacianHomogeneous n) :=
    laplacianHomogeneous_surjective n
  have hrange :
      Module.finrank ℝ (LinearMap.range (laplacianHomogeneous n)) =
        Module.finrank ℝ (homogeneousSubmodule n) := by
    rw [LinearMap.range_eq_top.2 hsurj]
    simpa using (Module.finrank_self ℝ (homogeneousSubmodule n))
  have hker :
      Module.finrank ℝ (LinearMap.ker (laplacianHomogeneous n)) =
        Module.finrank ℝ (harmonicHomogeneousSubmodule (n + 2)) := by
    simpa using (kerLaplacianHomogeneousEquivHarmonicHomogeneousSubmodule n).finrank_eq
  have hnull := LinearMap.finrank_range_add_finrank_ker (laplacianHomogeneous n)
  rw [hrange, hker, finrank_homogeneousSubmodule n,
    finrank_homogeneousSubmodule (n + 2)] at hnull
  have hstep := multichoose_three_two_step n
  omega

theorem finrank_harmonicHomogeneousSubmodule (n : ℕ) :
    Module.finrank ℝ (harmonicHomogeneousSubmodule n) = 2 * n + 1 := by
  rcases n with _ | _ | n
  · have hzero :
        harmonicHomogeneousSubmodule 0 = homogeneousSubmodule 0 := by
      refine le_antisymm inf_le_left ?_
      intro p hp
      exact mem_harmonicHomogeneousSubmodule_zero_of_mem_homogeneousSubmodule hp
    rw [hzero, finrank_homogeneousSubmodule]
    norm_num
  · have hone :
        harmonicHomogeneousSubmodule 1 = homogeneousSubmodule 1 := by
      refine le_antisymm inf_le_left ?_
      intro p hp
      exact mem_harmonicHomogeneousSubmodule_one_of_mem_homogeneousSubmodule hp
    rw [hone, finrank_homogeneousSubmodule]
    norm_num
  · simpa using finrank_harmonicHomogeneousSubmodule_succ_succ n

theorem restrictToSector_injective (n : ℕ) :
    Function.Injective (restrictToSector n) := by
  intro p q hpq
  apply Subtype.ext
  exact congrArg Subtype.val <|
    restrictToSphere_injective_on_harmonicHomogeneousSubmodule n <| by
      simpa [restrictToSector] using congrArg Subtype.val hpq

/-- Restriction to the sphere identifies harmonic homogeneous polynomials with the corresponding
continuous harmonic sector. -/
noncomputable def restrictToSectorEquiv (n : ℕ) :
    harmonicHomogeneousSubmodule n ≃ₗ[ℝ] sector n :=
  LinearEquiv.ofBijective (restrictToSector n)
    ⟨restrictToSector_injective n, restrictToSector_surjective n⟩

theorem finrank_sector (n : ℕ) :
    Module.finrank ℝ (sector n) = 2 * n + 1 := by
  rw [← (restrictToSectorEquiv n).finrank_eq]
  exact finrank_harmonicHomogeneousSubmodule n

theorem finrank_sectorL2 (n : ℕ) :
    Module.finrank ℝ (sectorL2 n) = 2 * n + 1 := by
  let e : sector n ≃ₗ[ℝ] sectorL2 n :=
    LinearEquiv.ofBijective (sectorToSectorL2 n) ⟨by
      intro f g hfg
      apply Subtype.ext
      exact ContinuousMap.toLp_injective rotationMeasure <| by
        simpa [sectorToSectorL2] using congrArg Subtype.val hfg, sectorToSectorL2_surjective n⟩
  rw [← e.finrank_eq]
  exact finrank_sector n

end SphericalHarmonics
