import Gleason.Harmonic.Sphere.S2FrameRotation
import SphericalHarmonics.GeometricDecomposition

noncomputable section

namespace GleasonS2Bridge

open SphericalHarmonics

/-- The `L²(S²)` image of the transported continuous frame-function submodule. -/
def continuousSphereFrameImageL2S2 : Submodule ℝ L2S2Geom :=
  Submodule.map continuousToLp.toLinearMap continuousSphereFrameSubmoduleS2

/-- The closed `L²(S²)` subspace generated by continuous frame functions. -/
def continuousSphereFrameClosedSubmoduleL2S2 : ClosedSubmodule ℝ L2S2Geom :=
  Submodule.closure continuousSphereFrameImageL2S2

theorem continuousSphereFrameImageL2S2_mapsTo_compL2Rotation (ρ : Rotation) :
    Set.MapsTo (Rotation.compL2Rotation ρ)
      (continuousSphereFrameImageL2S2 : Set L2S2Geom)
      (continuousSphereFrameImageL2S2 : Set L2S2Geom) := by
  intro x hx
  rcases hx with ⟨f, hf, rfl⟩
  refine ⟨Rotation.compContinuous ρ.symm f, ?_, ?_⟩
  · exact continuousSphereFrameSubmoduleS2_invariant_under_compContinuous ρ.symm hf
  · simpa using continuousToLp_compContinuous_symm ρ f

theorem continuousSphereFrameClosedSubmoduleL2S2_isRotationInvariant :
    ClosedSubmodule.IsRotationInvariant continuousSphereFrameClosedSubmoduleL2S2 := by
  intro ρ x hx
  have hmap :
      Set.MapsTo (Rotation.compL2Rotation ρ)
        (continuousSphereFrameImageL2S2 : Set L2S2Geom)
        (continuousSphereFrameClosedSubmoduleL2S2 : Set L2S2Geom) := by
    intro y hy
    exact subset_closure <| continuousSphereFrameImageL2S2_mapsTo_compL2Rotation ρ hy
  exact hmap.closure_left (Rotation.compL2Rotation ρ).continuous
    continuousSphereFrameClosedSubmoduleL2S2.isClosed hx

theorem continuousSphereFrameClosedSubmoduleL2S2_eq_topologicalClosure_iSup_inf_sectorL2 :
    continuousSphereFrameClosedSubmoduleL2S2.toSubmodule =
      (⨆ n : ℕ, continuousSphereFrameClosedSubmoduleL2S2.toSubmodule ⊓ sectorL2 n).topologicalClosure :=
  ClosedSubmodule.toSubmodule_eq_topologicalClosure_iSup_inf_sectorL2_of_isRotationInvariant
    continuousSphereFrameClosedSubmoduleL2S2
    continuousSphereFrameClosedSubmoduleL2S2_isRotationInvariant

end GleasonS2Bridge
